In [2]:
#Create a NumPy array containing numbers from 1 to 10.
import numpy as np
arr=np.array([1,2,3,4,56,7,8,9,10])
arr

array([ 1,  2,  3,  4, 56,  7,  8,  9, 10])

In [3]:
#Create a NumPy array containing the values:
arr=np.array([10,20,30,40,50,60])
arr

array([10, 20, 30, 40, 50, 60])

In [4]:
#Create a 1D array containing 5 zeros.
arr=np.zeros((1,5),dtype=int)
arr

array([[0, 0, 0, 0, 0]])

In [6]:
#Create a 1D array containing 5 ones.
arr=np.ones((1,5),dtype=int)
arr

array([[1, 1, 1, 1, 1]])

In [7]:
#Create a 3×3 array containing only zeros.
arr=np.zeros((3,3),dtype=int)
arr

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [8]:
#Create a 2×4 array containing only ones.
arr=np.ones((2,4),dtype=int)
arr

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [9]:
arr=np.arange(2,21,2)
arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [10]:
#Create a NumPy array containing numbers from 10 to 50 with a gap of 5.
arr=np.arange(10,51,5)
arr

array([10, 15, 20, 25, 30, 35, 40, 45, 50])

In [14]:
#Create a 3×3 identity matrix.
arr=np.array([1,2,3,4,5,6,7,8,9])
arr1=arr.reshape(3,3)
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
#Create a NumPy array from the Python list:[5, 10, 15, 20, 25].
lst=[5,10,15,20,25]
arr=np.array(lst)
arr

array([ 5, 10, 15, 20, 25])