In [38]:
import numpy as np
#Sort it in ascending order using np.sort().
arr=np.array([50, 20, 40, 10, 30])
np.sort(arr)

array([10, 20, 30, 40, 50])

In [39]:
#Sort the array in descending order.
arr=np.array([10, 5, 8, 20, 3])
np.sort(arr)[::-1]

array([20, 10,  8,  5,  3])

In [40]:
#Create an array from 1 to 20 in random order. Sort it in ascending order.
arr=np.random.randint(1,21,10)
np.sort(arr)

array([ 1,  2,  4,  7,  8, 11, 14, 15, 15, 17], dtype=int32)

In [41]:
#Find the sorted array without changing the original array.
arr=np.array([30, 10, 50, 20, 40])
print(arr)
duplicate=np.sort(arr)
print(duplicate)

[30 10 50 20 40]
[10 20 30 40 50]


In [42]:
#Sort the array and observe how duplicate values are handled.
arr=np.array([5, 2, 8, 2, 9, 5, 1])
print(arr)
arr2=np.sort(arr)
print(arr2)
np.unique(arr2,return_counts=True)

[5 2 8 2 9 5 1]
[1 2 2 5 5 8 9]


(array([1, 2, 5, 8, 9]), array([1, 2, 2, 1, 1]))

In [43]:
#Sort each row in ascending order.
arr = np.array([
    [30, 10, 20],
    [60, 40, 50],
    [90, 70, 80]
])
print(np.sort(arr,axis=1))

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [44]:
#Using the same array, sort each column in ascending order.
arr = np.array([
    [30, 10, 20],
    [60, 40, 50],
    [90, 70, 80]
])
print(np.sort(arr,axis=0))

[[30 10 20]
 [60 40 50]
 [90 70 80]]


In [45]:
#Sort each row in ascending order.
arr = np.array([
    [50, 20, 80],
    [30, 90, 10],
    [70, 40, 60]
])
print(np.sort(arr,axis=1))

[[20 50 80]
 [10 30 90]
 [40 60 70]]


In [46]:
#Sort the columns of the same array in descending order.
arr = np.array([
    [50, 20, 80],
    [30, 90, 10],
    [70, 40, 60]
])
result=np.sort(arr,axis=0)[::-1]
print(result)

[[70 90 80]
 [50 40 60]
 [30 20 10]]


In [47]:
#Create a 4×5 random integer array between 1 and 100. Sort each row.
arr=np.random.randint(1,101,(4,5))
print(np.sort(arr,axis=1))

[[ 12  31  51  57  58]
 [ 42  49  60  73 100]
 [  5  17  43  66  86]
 [  2  14  33  51  82]]


In [49]:
#Find the sorted array and then find its minimum and maximum.
arr=np.array([10, 50, 20, 80, 30])
print(np.sort(arr))
print(f"Minimum:{arr.min()}")
print(f"Maximum:{arr.max()}")

[10 20 30 50 80]
Minimum:10
Maximum:80


In [50]:
#Sort it and find the second-smallest value.
arr=np.array([40, 10, 70, 20, 90, 30])
result=np.sort(arr)
print(result)
print(f"Second Smallest Element:{result[1]}")

[10 20 30 40 70 90]
Second Smallest Element:20


In [51]:
#Sort it and find the second-largest value.
arr=np.array([40, 10, 70, 20, 90, 30])
result=np.sort(arr)
print(result)
print(f"Second Largest Value:{result[-2]}")

[10 20 30 40 70 90]
Second Largest Value:70


In [56]:
#Create an array from 1 to 20 in random order. Sort it and calculate the median.
arr=np.random.randint(1,21,10)
result=np.sort(arr)
print(result)
print(f"Median:{np.median(result)}")

[ 1  2  4  9 12 13 14 16 18 19]
Median:12.5


In [60]:
#Generate 10 random integers between 1 and 100. Sort them and print the first 3 smallest values.
arr=np.random.randint(1,100,10)
result=np.sort(arr)
print(result)
print(f"First three smallest values:{result[:3]}")

[12 28 31 32 50 65 65 68 88 91]
First three smallest values:[12 28 31]


In [64]:
#Filter values greater than 30, then sort the filtered values.
arr=np.array([10, 45, 20, 80, 35, 60, 15])
greter=arr[arr>30]
print(greter)
print(np.sort(greter))

[45 80 35 60]
[35 45 60 80]


In [66]:
#Create an array from 1 to 50 in random order. Filter all even numbers, then sort them.
arr=np.random.randint(1,50,10)
print(arr)
even=arr[arr%2==0]
print(even)
print(np.sort(even))

[24 31 38 12 32 26 23 28 33 32]
[24 38 12 32 26 28 32]
[12 24 26 28 32 32 38]


In [69]:
#Generate 20 random integers between 1 and 100. Filter numbers greater than 50, then sort them in descending order.
arr=np.random.randint(1,100,20)
print(arr)
greter=arr[arr>50]
print(greter)
print(np.sort(greter)[::-1])

[ 8 17 53 64 21 82 27 81 37 63 80 62 42 12  5 27  9 70 82 13]
[53 64 82 81 63 80 62 70 82]
[82 82 81 80 70 64 63 62 53]
