In [3]:
import numpy as np

In [4]:
#Add 10 to every element:
arr = np.array([1, 2, 3, 4, 5])
arr+10

array([11, 12, 13, 14, 15])

In [5]:
#Multiply every element by 5:
arr = np.array([2, 4, 6, 8])
arr*5

array([10, 20, 30, 40])

In [6]:
#Subtract 10 from every element:
arr = np.array([20, 30, 40, 50])
arr-10

array([10, 20, 30, 40])

In [7]:
#Divide every element by 2:
arr = np.array([10, 20, 30, 40])
arr/2

array([ 5., 10., 15., 20.])

In [8]:
#Add 5 to every element of this 2D array:
arr = np.array([
    [10, 20, 30],
    [40, 50, 60]
])
arr+5

array([[15, 25, 35],
       [45, 55, 65]])

In [9]:
#Add [10, 20, 30] to every row:
arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
arr+np.array([10,20,30])

array([[11, 22, 33],
       [14, 25, 36]])

In [10]:
#Multiply every column by [2, 3, 4]:
arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
arr*np.array([2,3,4])

array([[ 2,  6, 12],
       [ 8, 15, 24]])

In [11]:
#Subtract [5, 10, 15] from every row:
arr = np.array([
    [20, 30, 40],
    [50, 60, 70]
])
arr-np.array([5,10,15])

array([[15, 20, 25],
       [45, 50, 55]])

In [12]:
#Divide every column by [1, 2, 5]:
arr = np.array([
    [10, 20, 50],
    [20, 40, 100]
])
arr/np.array([1,2,5])

array([[10., 10., 10.],
       [20., 20., 20.]])

In [13]:
#Add [100, 200, 300] to each row of a 3×3 array.
np.arange(1,10).reshape(3,3)+np.array([100,200,300])

array([[101, 202, 303],
       [104, 205, 306],
       [107, 208, 309]])

In [16]:
#Add a column vector to every column:
arr = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

values = np.array([
    [10],
    [20],
    [30]
])

arr+values

array([[11, 12, 13],
       [24, 25, 26],
       [37, 38, 39]])

In [17]:
#Multiply each row by a different value:
arr = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

values = np.array([
    [2],
    [3],
    [4]
])
arr*values

array([[ 2,  4,  6],
       [12, 15, 18],
       [28, 32, 36]])

In [21]:
#Add the following row vector to a 4×3 array:
np.arange(1,13).reshape(4,3)
values = np.array([10, 20, 30])
arr+values

array([[11, 22, 33],
       [14, 25, 36],
       [17, 28, 39]])

In [22]:
#Subtract the following column vector from a 3×4 array:
arr=np.arange(1,13).reshape(3,4)
values = np.array([
    [5],
    [10],
    [15]
])
arr-values

array([[-4, -3, -2, -1],
       [-5, -4, -3, -2],
       [-6, -5, -4, -3]])

In [25]:
#Create a 3×4 array of numbers from 1–12 and multiply each column by:
arr=np.arange(1,13).reshape(3,4)
arr*np.array([1, 2, 3, 4])

array([[ 1,  4,  9, 16],
       [ 5, 12, 21, 32],
       [ 9, 20, 33, 48]])

In [30]:
#Create a 3×3 array and add 10 to every element using broadcasting. Then find its maximum and minimum.
arr=np.arange(1,10).reshape(3,3)
val=arr+10
print(val)
print(f"Minimum:{val.min()}")
print(f"Maximim:{val.max()}")

[[11 12 13]
 [14 15 16]
 [17 18 19]]
Minimum:11
Maximim:19


In [35]:
#Create a 4×3 random array between 1–50. Add:
arr=np.random.randint(1,50,(4,3))
arr+np.array([10, 20, 30])


array([[43, 31, 59],
       [49, 21, 34],
       [58, 69, 66],
       [34, 30, 39]])

In [36]:
#Create a 3×4 random array between 1–100. Subtract:
arr=np.random.randint(1,100,(3,4))
arr-np.array([[10],
              [20],
              [30]])

array([[ 29,   2,  19,  21],
       [ 78, -16,  21,  60],
       [ 63,  64,  63,  62]])

In [37]:
#Create:
arr = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

#Multiply each row by:
arr*np.array([1, 2, 3])


array([[ 10,  40,  90],
       [ 40, 100, 180],
       [ 70, 160, 270]])

In [60]:
#Challenge: Create a 4×3 random array between 1–100. Add [10, 20, 30] to every row, then:
# Find the maximum value
# Find the minimum value
# Find the mean
# Sort each row

# Important patterns to remember:

# arr + 10
# arr * 5
# arr + np.array([10, 20, 30])
# arr + np.array([[10], [20], [30]])
arr=np.random.randint(1,100,(4,3))
val=arr+np.array([10,20,30])
print(val)
print(f"Minimum:{val.min()}")
print(f"Maximum:{val.max()}")
print(f"Mean:{val.mean()}")
print(f"After Sorting:{np.sort(val,axis=1)}")
print("-----------------------")
print( arr + 10)
print("-----------------------")
print(arr*5)
print("-----------------------")
print(arr + np.array([10, 20, 30]))
print("-----------------------")
print(arr + np.array([[10], 
                      [20], 
                      [30],
                      [40]]))

[[ 77  39  49]
 [ 14 107 114]
 [ 52  79  61]
 [ 87  71 105]]
Minimum:14
Maximum:114
Mean:71.25
After Sorting:[[ 39  49  77]
 [ 14 107 114]
 [ 52  61  79]
 [ 71  87 105]]
-----------------------
[[77 29 29]
 [14 97 94]
 [52 69 41]
 [87 61 85]]
-----------------------
[[335  95  95]
 [ 20 435 420]
 [210 295 155]
 [385 255 375]]
-----------------------
[[ 77  39  49]
 [ 14 107 114]
 [ 52  79  61]
 [ 87  71 105]]
-----------------------
[[ 77  29  29]
 [ 24 107 104]
 [ 72  89  61]
 [117  91 115]]
