In [6]:
#Create an array [10, 20, 30, 40, 50] and find its:Number of dimensions Shape Size Data type
import numpy as np
arr=np.array([10,20,30,40,50])
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)

1
(5,)
5
int64


In [9]:
#Create a 3×4 array and find its ndim, shape, and size.
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
arr1=arr.reshape(3,4)
arr1
print(arr1.ndim)
print(arr1.shape)
print(arr1.size)

2
(3, 4)
12


In [11]:
#Create a 2×3×4 array and find its:Dimensions Shape Total number of elements
arr=np.ones((2,3,4),dtype=int)
arr
print(f"Dimension:{arr.ndim}")
print(f"Shape:{arr.shape}")
print(f"Total number of elements:{arr.size}")

Dimension:3
Shape:(2, 3, 4)
Total number of elements:24


In [12]:
#Create an array containing numbers from 1 to 12 and reshape it into a 3×4 array. Check its properties.
arr=np.arange(1,13).reshape(3,4)
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [13]:
#Create a 5×5 array of zeros and display its shape and size.
arr=np.zeros((5,5),dtype=int)
arr

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [18]:
#Create an array of 10 floating-point numbers and check its data type.
arr=np.ones((10))
print(f"Data Type:{arr.dtype}")
arr

Data Type:float64


array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [19]:
#Create an integer array and check its data type.
arr=np.array([2,4,6,7,8,9,0])
print(f"Integer Data Type:{arr.dtype}")
arr

Integer Data Type:int64


array([2, 4, 6, 7, 8, 9, 0])

In [21]:
#Create a 2×5 array and calculate how many elements it contains using its properties.
arr=np.arange(1,11).reshape(2,5)
print(f"Number of elements:{arr.size}")

Number of elements:10


In [28]:
#Create a 3D array and identify whether it is 1D, 2D, or 3D using its property.
arr=np.zeros((2,2,5),dtype=int)
print(arr.ndim)
arr

3


array([[[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]]])