In [ ]:
import numpy as np
from numpy.random import default_rng

In [9]:
#Generate 5 random numbers between 0 and 1.
rng=default_rng(42)
values=rng.random(5)
values

array([0.77395605, 0.43887844, 0.85859792, 0.69736803, 0.09417735])

In [3]:
#Generate a 3×3 array containing random numbers between 0 and 1.
arr=np.random.rand(3,3)
arr

array([[0.93243799, 0.31632558, 0.31760838],
       [0.80280327, 0.10807532, 0.94847946],
       [0.16579573, 0.31792932, 0.73899158]])

In [13]:
#Generate 10 random integers between 1 and 100.
arr=np.random.randint(1,101,10)
arr

array([67, 95, 84,  8, 48, 33, 55, 49, 69, 98], dtype=int32)

In [21]:
#Generate a 5×5 array of random integers between 1 and 50.
arr=np.random.randint(1,51,(5,5))
arr


array([[15, 44,  6, 34, 10],
       [50,  6, 25, 28, 38],
       [28, 10,  8, 29, 45],
       [35, 50, 28,  1, 36],
       [50, 10,  9, 14, 26]], dtype=int32)

In [22]:
#Generate 3 random integers between 10 and 20.
arr=np.random.randint(10,21,(3))
arr

array([12, 11, 18], dtype=int32)

In [23]:
#Generate a 2×4 array of random integers between 1 and 10.
arr=np.random.randint(1,11,(2,4))
arr

array([[10,  8,  6,  5],
       [ 2,  1,  4,  4]], dtype=int32)

In [26]:
#Generate 10 random numbers and find the array's:Shape Size Data type
arr=np.random.rand(10)
arr
print(f"Shape:{arr.shape}")
print(f"Size:{arr.size}")
print(f"Data Type:{arr.dtype}")

Shape:(10,)
Size:10
Data Type:float64


In [32]:
#Generate a 3×3 random integer array and find its maximum and minimum values.
arr=np.random.randint(1,15,(3,3))
print(arr)
print(f"Maximum:{arr.max()}")
print(f"Minimun:{arr.min()}")


[[10 13  5]
 [11  9  2]
 [13  5  2]]
Maximum:13
Minimun:2


In [2]:
#Generate a 4×5 random integer array and check all its NumPy properties.
import numpy as np
arr=np.random.randint(1,21,(4,5))
print(f"Shape:{arr.shape}")
print(f"Size:{arr.size}")
print(f"Dimension:{arr.ndim}")
print(f"Data Type:{arr.dtype}")


Shape:(4, 5)
Size:20
Dimension:2
Data Type:int32


In [2]:
#Create a 3×3 random matrix containing numbers between 1 and 100, then display:
# The matrix
# Number of dimensions
# Shape
# Size
# Data type
# Maximum value
# Minimum value
import numpy as np
arr=np.random.randint(1,101,(3,3))
print(arr)
print(f"Dimention:{arr.ndim}")
print(f"Shape:{arr.shape}")
print(f"Size:{arr.size}")
print(f"Data Type:{arr.dtype}")
print(f"Maximim:{arr.max()}")
print(f"Minimum:{arr.min()}")

[[66 95 82]
 [15 89 88]
 [63 37 60]]
Dimention:2
Shape:(3, 3)
Size:9
Data Type:int32
Maximim:95
Minimum:15
