In [ ]:
""
From the array below, print every second column:
[[1, 2, 3, 4, 5],
 [6, 7, 8, 9, 10],
 [11, 12, 13, 14, 15]]
Challenge: Create a 5×5 NumPy array containing numbers from 1 to 25 and extract only the center 3×3 matrix:
[[ 7,  8,  9],
 [12, 13, 14],
 [17, 18, 19]]
"""

In [3]:
import numpy as np
#Create a NumPy array [10, 20, 30, 40, 50]. Print the first element.
arr=np.array([10, 20, 30, 40, 50])
print(arr[0])

10


In [4]:
#Print the last element of the array [10, 20, 30, 40, 50].
arr=np.array([10,20,30,40,50])
print(arr[-1])

50


In [5]:
#Print the third element of [5, 10, 15, 20, 25].
arr=np.array([5, 10, 15, 20, 25])
print(arr[2])

15


In [7]:
#Print the second-last element of [10, 20, 30, 40, 50, 60] using negative indexing.
arr=np.array([10,20,30,40,50,60])
print(arr[-2])

50


In [8]:
#Create an array from 1 to 10 and print the elements at index 2, 5, and 8.
arr=np.array([1,2,3,4,5,6,7,8,9,10])
print(arr[2])
print(arr[5])
print(arr[8])

3
6
9


In [2]:
#Create an array from 1 to 10 and print the first 5 elements.
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10])
print(arr[:5])

[1 2 3 4 5]


In [8]:
#Create an array from 1 to 10 and print the last 5 elements using slicing.
arr=np.array([1,2,3,4,5,6,7,8,9,10])
print(arr[:-6:-1])

[10  9  8  7  6]


In [9]:
#Print elements from index 2 to index 6 from:
arr=np.array([10, 20, 30, 40, 50, 60, 70, 80])
print(arr[2:7])

[30 40 50 60 70]


In [12]:
#Print every second element from:
arr=np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(arr[1::2])

[ 2  4  6  8 10]


In [13]:
#Reverse the array [1, 2, 3, 4, 5, 6, 7, 8, 9, 10] using slicing.
arr=np.array([1,2,3,4,5,6,7,8,9,10])
print(arr[::-1])

[10  9  8  7  6  5  4  3  2  1]


In [15]:
#Create this 2D array:Print 50.
arr=np.array([[10,20,30],
                [40,50,60],
                [70,80,90]])
print(arr[1,1])

50


In [17]:
#Using the same array, print 30.
arr=np.array([[10,20,30],
                [40,50,60],
                [70,80,90]])
print(arr[0,-1])

30


In [18]:
#Using the same array, print the last element of the second row.
arr=np.array([[10,20,30],
                [40,50,60],
                [70,80,90]])
print(arr[1,-1])

60


In [19]:
#Using the same array, print the first element of the third row.
arr=np.array([[10,20,30],
                [40,50,60],
                [70,80,90]])
print(arr[2,0])

70


In [20]:
#Using the same array, print the entire second row.
arr=np.array([[10,20,30],
                [40,50,60],
                [70,80,90]])
print(arr[1])

[40 50 60]


In [22]:
#extract the first two rows.
arr=np.array([[10, 20, 30, 40],
 [50, 60, 70, 80],
 [90, 100, 110, 120]])
print(arr[0])

[10 20 30 40]


In [29]:
#From the same array, extract the last two columns.
arr=np.array([[10, 20, 30, 40],
                [50, 60, 70, 80],
                [90, 100, 110, 120]])
print(arr[:,-2::])

[[ 30  40]
 [ 70  80]
 [110 120]]


In [33]:
#Extract this portion:[[60, 70],[100, 110]]
arr=np.array([[10, 20, 30, 40],
                [50, 60, 70, 80],
                [90, 100, 110, 120]])
print(arr[1:3,1:3])

[[ 60  70]
 [100 110]]
