In [2]:
import numpy as np
arr1=np.array([10,20,30,40,50])
arr2=np.array([1,2,3,4,5])

In [ ]:
#Add a Scalar
Add=arr1+2
Add

array([12, 22, 32, 42, 52])

In [4]:
#Substract a Scalar
Sub=arr1-2
Sub

array([ 8, 18, 28, 38, 48])

In [ ]:
#Multiply by a Scalar
Mul=arr1*2
Mul

array([ 20,  40,  60,  80, 100])

In [6]:
#Divide by a Scalar
Div=arr1/2
Div

array([ 5., 10., 15., 20., 25.])

In [ ]:
#Element wise addition
Add=arr1+arr2
Add

array([11, 22, 33, 44, 55])

In [8]:
#Element wise multiplication
Mul=arr1*arr2
Mul

array([ 10,  40,  90, 160, 250])