In [21]:
"""

"""

'\n\n'

In [22]:
import numpy as np


In [23]:
#Print all elements greater than 25.
Ages=np.array([2,5,25,7,9,10,53,80,56,30,7,10,49,50,60])
Adult_mask=Ages>=25
Ages[Adult_mask]

array([25, 53, 80, 56, 30, 49, 50, 60])

In [24]:
#filter and print all elements less than 20.
Ages=np.array([2,5,25,7,9,10,53,80,56,30,7,10,49,50,60])
Teen_mask=Ages<=20
Ages[Teen_mask]

array([ 2,  5,  7,  9, 10,  7, 10])

In [25]:
#print all elements greater than or equal to 30.
Ages=np.array([30,2,5,25,7,9,10,53,80,30,56,30,7,10,49,30,50,60])
Adults=Ages>=30
Ages[Adults]

array([30, 53, 80, 30, 56, 30, 49, 30, 50, 60])

In [26]:
#print all elements less than or equal to 25.
Ages=np.array([30,2,5,25,7,9,10,53,80,30,56,30,7,10,49,30,50,60])
Teen=Ages<=25
Ages[Teen]

array([ 2,  5, 25,  7,  9, 10,  7, 10])

In [27]:
#filter only the element equal to 30.
Ages=np.array([30,2,5,25,7,9,10,53,80,30,56,30,7,10,49,30,50,60])
Arr=Ages==30
Ages[Arr]

array([30, 30, 30, 30])

In [28]:
#print numbers that are greater than 15 AND less than 35.
arr=np.array([10, 15, 20, 25, 30, 35, 40])
Age=(arr>=15) & (arr<=35)
arr[Age]

array([15, 20, 25, 30, 35])

In [29]:
#Create an array from 1 to 30 and print numbers that are:
#Greater than 10
#AND even
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30])
a=(arr>=10) & (arr%2==0)
arr[a]

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

In [30]:
#Create an array from 1 to 50 and print numbers that are:
#Less than 20
#OR greater than 40
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50])
b=(arr<=20) | (arr>=40)
arr[b]


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [31]:
#print numbers that are divisible by both 2 and 3.
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50])
a=(arr%2==0) & (arr%3==0)
arr[a]

array([ 6, 12, 18, 24, 30, 36, 42, 48])

In [32]:
#Create an array from 1 to 50 and print numbers that are divisible by 3 OR 5.
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50])
a=(arr%3==0) & (arr%5==0)
arr[a]

array([15, 30, 45])

In [33]:
#Print all elements greater than 50.
arr = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])
a=arr>50
arr[a]

array([60, 70, 80, 90])

In [34]:
#Using the same array, print all elements less than 50.
arr = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])
a=arr<50
arr[a]

array([10, 20, 30, 40])

In [35]:
#Create a 4×4 array containing numbers from 1 to 16 and print all even numbers.
arr=np.arange(1,17).reshape(4,4)
a=arr%2==0
arr[a]

array([ 2,  4,  6,  8, 10, 12, 14, 16])

In [36]:
#Create a 3×4 array containing numbers from 1 to 12 and print all numbers greater than 5 and less than 11.
arr=np.arange(1,13).reshape(3,4)
a=(arr>5) & (arr<11)
arr[a]

array([ 6,  7,  8,  9, 10])

In [47]:
#Create a NumPy array containing 20 random integers between 1 and 100.
#Then filter and display:
#Numbers greater than 50
#Even numbers
#Numbers between 20 and 70
#Numbers divisible by 5
arr=np.random.randint(1,101,20)
print(f"Numbers greater than 50:{arr[arr>50]}")
print(f"Even numbers:{arr[arr%2==0]}")
a=(arr>=20) & (arr<=70)
print(arr[a])
b=arr%5==0
print(arr[b])

Numbers greater than 50:[ 64  84  67  99  62  74  78 100  93  90  56  60  97]
Even numbers:[  6  64  84  62  46  74  78 100  22  90  56  60]
[64 67 62 46 49 22 27 56 60]
[100  90  60]
