In [1]:
import numpy as np
#Change the third element from 30 to 100.
arr=np.array([10, 20, 30, 40, 50])
arr[2]=100
arr

array([ 10,  20, 100,  40,  50])

In [2]:
#Change the first element to 50 and the last element to 100.
arr=np.array([5, 10, 15, 20, 25])
arr[[0,-1]]=[50,100]
arr

array([ 50,  10,  15,  20, 100])

In [3]:
#Create an array from 1 to 10. Change all elements from index 2 to index 5 to 0.
arr=np.array([1,2,3,4,5,6,7,8,9,10])
arr[2:6]=0
arr

array([ 1,  2,  0,  0,  0,  0,  7,  8,  9, 10])

In [4]:
#Multiply every element by 2 and update the original array.
arr=np.array([10,20,30,40,50])
print(f"Before Updating:{arr}")
a=arr*2
print(f"After Updating:{a}")

Before Updating:[10 20 30 40 50]
After Updating:[ 20  40  60  80 100]


In [5]:
#Create an array from 1 to 10. Replace all even numbers with 0.
arr=np.array([1,2,3,4,5,6,7,8,9,10])
arr[arr%2==0]=0
arr

array([1, 0, 3, 0, 5, 0, 7, 0, 9, 0])

In [6]:
#Create an array from 1 to 20. Replace all numbers greater than 10 with 100.
arr=np.arange(1,21)
arr[arr>10]=100
arr

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10, 100, 100, 100,
       100, 100, 100, 100, 100, 100, 100])

In [7]:
#Change the value 50 to 500.
arr = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])
arr[arr==50]=500
arr

array([[ 10,  20,  30],
       [ 40, 500,  60],
       [ 70,  80,  90]])

In [8]:
#Using the same 2D array, change the entire second row to:
#[100, 200, 300]
arr = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])
arr[[1]]=[100,200,300]
arr

array([[ 10,  20,  30],
       [100, 200, 300],
       [ 70,  80,  90]])

In [9]:
#Create a 4×4 array containing numbers from 1 to 16. Replace all numbers greater than 10 with -1.
arr=np.arange(1,17).reshape(4,4)
arr[arr>10]=-1
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, -1, -1],
       [-1, -1, -1, -1]])

In [19]:
#Challenge: Create a NumPy array containing 20 random integers between 1 and 100. Replace every number less than 50 with 0 and every number greater than or equal to 50 with 1.
arr=np.random.randint(1,101,20)
arr[arr<50]=0 
arr[arr>=50]=-1
arr

array([-1,  0, -1,  0,  0, -1,  0, -1, -1, -1,  0,  0,  0,  0,  0,  0,  0,
       -1, -1, -1], dtype=int32)