In [3]:
import numpy as np
#Create an array [10, 20, 30, 40, 50]. Use np.where() to find the indexes of elements greater than 25.
arr=np.array([10, 20, 30, 40, 50])
index=np.where(arr>25)
index

(array([2, 3, 4]),)

In [4]:
#Create an array [5, 10, 15, 20, 25]. Find the indexes of elements less than 15.
arr=np.array([5, 10, 15, 20, 25])
index=np.where(arr<15)
index

(array([0, 1]),)

In [9]:
#Create an array [10, 20, 30, 40, 50]. Find the indexes of elements equal to 30.
arr=np.array([10, 20, 30, 40, 50])
index=np.where(arr==30)
index

(array([2]),)

In [18]:
#Create an array from 1 to 20. Find the indexes of all even numbers.
arr=np.arange(1,21)
print(arr)
even=np.where(arr%2==0)
even

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


(array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19]),)

In [19]:
#Create an array from 1 to 20. Find the indexes of all odd numbers.
arr=np.arange(1,21)
odd=np.where(arr%2==1)
odd


(array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18]),)

In [20]:
#Create an array from 1 to 10. Replace all even numbers with 0 and odd numbers with 1 using np.where().
arr=np.arange(1,11)
even_odd=np.where(arr%2==0,0,1)
even_odd

array([1, 0, 1, 0, 1, 0, 1, 0, 1, 0])

In [21]:
#Create an array [10, 20, 30, 40, 50]. Replace values greater than 30 with 100, otherwise keep the original value.
arr=np.array([10, 20, 30, 40, 50])
greater=np.where(arr>30,100,arr)
greater

array([ 10,  20,  30, 100, 100])

In [22]:
#Create an array [5, 15, 25, 35, 45]. Replace values less than 25 with -1, otherwise keep the original value.
arr=np.array([5, 15, 25, 35, 45])
lessthen=np.where(arr<25,-1,arr)
lessthen

array([-1, -1, 25, 35, 45])

In [23]:
#Create an array from 1 to 20. Convert:
#Even → 100
#Odd → 200
arr=np.arange(1,21)
even_odd=np.where(arr%2==0,100,200)
even_odd

array([200, 100, 200, 100, 200, 100, 200, 100, 200, 100, 200, 100, 200,
       100, 200, 100, 200, 100, 200, 100])

In [24]:
#Create an array [10, 25, 40, 55, 70]. Replace values greater than or equal to 40 with 1, otherwise 0
arr=np.array([10, 25, 40, 55, 70])
equal=np.where(arr>=40,1,0)
equal

array([0, 0, 1, 1, 1])

In [38]:
#Create an array from 1 to 30. Using np.where(), replace numbers between 10 and 20 with 100.
arr=np.arange(1,31)
replace=np.where((arr>=10) & (arr<=20),100,arr)
print(replace)

[  1   2   3   4   5   6   7   8   9 100 100 100 100 100 100 100 100 100
 100 100  21  22  23  24  25  26  27  28  29  30]


In [40]:
#Create an array from 1 to 50. Replace numbers divisible by 5 with 0, otherwise keep the original values.
arr=np.arange(1,51)
replace=np.where(arr%5==0,0,arr)
replace

array([ 1,  2,  3,  4,  0,  6,  7,  8,  9,  0, 11, 12, 13, 14,  0, 16, 17,
       18, 19,  0, 21, 22, 23, 24,  0, 26, 27, 28, 29,  0, 31, 32, 33, 34,
        0, 36, 37, 38, 39,  0, 41, 42, 43, 44,  0, 46, 47, 48, 49,  0])

In [42]:
#Create an array from 1 to 30. Replace numbers that are both even and greater than 10 with -1.
arr=np.arange(1,31)
replace=np.where((arr%2==0) & (arr>10),-1,arr)
replace

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, -1, 13, -1, 15, -1, 17,
       -1, 19, -1, 21, -1, 23, -1, 25, -1, 27, -1, 29, -1])

In [43]:
#Create an array from 1 to 50. Replace numbers that are divisible by 3 OR 5 with 0.
arr=np.arange(1,51)
replace=np.where((arr%3==0) & (arr%5==0),0,arr)
replace

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14,  0, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29,  0, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44,  0, 46, 47, 48, 49, 50])

In [45]:
#Replace numbers greater than 20 AND less than 40 with 999.
arr=np.array([10, 15, 20, 25, 30, 35, 40])
replace=np.where((arr>20) & (arr<40),999,arr)
replace

array([ 10,  15,  20, 999, 999, 999,  40])

In [47]:
#Use np.where() to find the positions of values greater than 40.
arr=np.array([10, 25, 30, 45, 50, 65])
position=np.where(arr>40)
position

(array([3, 4, 5]),)

In [49]:
#Create an array from 1 to 100. Find the positions of numbers divisible by 10.
arr=np.arange(1,101)
position=np.where(arr%10==0)
position


(array([ 9, 19, 29, 39, 49, 59, 69, 79, 89, 99]),)

In [50]:
#Find the indexes of numbers divisible by both 2 and 3.
arr=np.array([5, 12, 18, 21, 30, 35, 42])
position=np.where((arr%2==0) & (arr%3==0))
position

(array([1, 2, 4, 6]),)

In [52]:
#Create an array from 1 to 50. Find the indexes of numbers between 20 and 30.
arr=np.arange(1,51)
position=np.where((arr>=20) & (arr<=30))
position

(array([19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]),)

In [58]:
#Create an array of 20 random integers between 1 and 100. Find the indexes of values greater than 75
arr=np.random.randint(1,101,20)
position=np.where(arr>75)
position

(array([ 0,  1,  8, 11, 17, 18]),)

In [ ]:
#Use np.where() to find the positions of values greater than 50.
arr = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])
position=np.where(arr>50)
position

(array([1, 2, 2, 2]), array([2, 0, 1, 2]))

In [61]:
#Using the same array, replace all values greater than 50 with 0.
arr = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])
replace=np.where(arr>50,0,arr)
replace

array([[10, 20, 30],
       [40, 50,  0],
       [ 0,  0,  0]])

In [62]:
#Using the same array, replace all values less than or equal to 40 with -1.
arr = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])
replace=np.where(arr<=40,-1,arr)
replace

array([[-1, -1, -1],
       [-1, 50, 60],
       [70, 80, 90]])

In [66]:
#Create a 4×4 array containing numbers from 1 to 16. Replace all even numbers with 0 and odd numbers with 1.
arr=np.arange(1,17).reshape(4,4)
print(arr)
replace=np.where(arr%2==0,0,1)
replace

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


array([[1, 0, 1, 0],
       [1, 0, 1, 0],
       [1, 0, 1, 0],
       [1, 0, 1, 0]])

In [68]:
#Create a 3×4 array containing numbers from 1 to 12. Find the row and column positions of values greater than 7.
arr=np.arange(1,13).reshape(3,4)
print(arr)
position=np.where(arr>7)
position

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


(array([1, 2, 2, 2, 2]), array([3, 0, 1, 2, 3]))

In [71]:
#Generate 10 random integers between 1 and 100. Using np.where(), replace:
#< 50 → 0
#>= 50 → 1
arr=np.random.randint(1,101,10)
print(arr)
replace=np.where(arr<50,0,np.where(arr>=50,1,arr))
replace

[99 81 74 36 57 66 76 32 89 93]


array([1, 1, 1, 0, 1, 1, 1, 0, 1, 1], dtype=int32)

In [77]:
#Generate a 5×5 random integer array between 1 and 100. Replace values greater than 80 with 100, otherwise keep the original values.
arr=np.random.randint(1,101,(5,5))
print(arr)
replace=np.where(arr>80,100,arr)
replace

[[79 65 84 74  9]
 [68  6 14 54 86]
 [35  3 87 38 45]
 [13 41 69 80 18]
 [83 68 14 55 72]]


array([[ 79,  65, 100,  74,   9],
       [ 68,   6,  14,  54, 100],
       [ 35,   3, 100,  38,  45],
       [ 13,  41,  69,  80,  18],
       [100,  68,  14,  55,  72]], dtype=int32)

In [81]:
#Generate 20 random integers between 1 and 100. Use np.where() to classify them as:
#< 30 → "Low"
#30–70 → "Medium"
#> 70 → "High"
arr=np.random.randint(1,101,20)
print(arr)
classify=np.where(arr<30,"Low",np.where((arr>=30) & (arr<=70),"Medium",np.where(arr>70,"High",arr)))
classify

[43 11 66 35 21 69  7 27 33 78 46  7 75 43 63 81 29 75 79 10]


array(['Medium', 'Low', 'Medium', 'Medium', 'Low', 'Medium', 'Low', 'Low',
       'Medium', 'High', 'Medium', 'Low', 'High', 'Medium', 'Medium',
       'High', 'Low', 'High', 'High', 'Low'], dtype='<U11')

In [ ]:
"""


"""

'\n\nChallenge: Generate a 4×5 random integer array between 1 and 100. Create a new array using np.where() where:\n< 30 → 0\n30–60 → 1\n> 60 → 2\n'

In [84]:
#Create an array from 1 to 50. Using only np.where(), create a new array where:
#Numbers divisible by 3 → 300
#Numbers divisible by 5 → 500
#All other numbers → 0
arr=np.arange(1,51)
print(arr)
modify=np.where(arr%3==0,300,np.where(arr%5==0,500,0))
modify

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50]


array([  0,   0, 300,   0, 500, 300,   0,   0, 300, 500,   0, 300,   0,
         0, 300,   0,   0, 300,   0, 500, 300,   0,   0, 300, 500,   0,
       300,   0,   0, 300,   0,   0, 300,   0, 500, 300,   0,   0, 300,
       500,   0, 300,   0,   0, 300,   0,   0, 300,   0, 500])

In [87]:
#Challenge: Generate a 4×5 random integer array between 1 and 100. Create a new array using np.where() where:
#< 30 → 0#
#30–60 → 1
#> 60 → 2
arr=np.random.randint(1,101,(4,5))
print(arr)
modify=np.where(arr<30,0,
                np.where((arr>=30) & (arr<=60),1,
                         np.where(arr>60,2,arr)))
modify

[[80 84 48 71 77]
 [71 34 90 31 95]
 [ 7 89 72 73  4]
 [86 23 96 32 57]]


array([[2, 2, 1, 2, 2],
       [2, 1, 2, 1, 2],
       [0, 2, 2, 2, 0],
       [2, 0, 2, 1, 1]], dtype=int32)