In [2]:
import numpy as np

In [3]:
#Create an array [10, 20, 30, 40, 50] and find its sum using .sum().
arr=np.array([10, 20, 30, 40, 50])
arr.sum()

np.int64(150)

In [4]:
#Find the minimum value of:
arr=np.array([25, 10, 45, 5, 30])
arr.min()

np.int64(5)

In [5]:
#Find the maximum value of:
arr=np.array([25, 10, 45, 5, 30])
arr.max()

np.int64(45)

In [6]:
#Find the mean (average) of:
arr=np.array([10, 20, 30, 40, 50])
arr.mean()


np.float64(30.0)

In [7]:
#Find the median of:
arr=np.array([10, 20, 30, 40, 50])
np.median(arr)

np.float64(30.0)

In [8]:
#Find the standard deviation of:
arr=np.array([10, 20, 30, 40, 50])
arr.std()

np.float64(14.142135623730951)

In [ ]:
#Create an array from 1 to 100 and find its:
#Sum
#Minimum
#Maximum
#Mean
arr=np.arange(1,101)
print(arr.sum())
print(arr.min())
print(arr.max())
print(arr.mean())

5050
1
100
50.5


In [11]:
#Find the total sum.
arr = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])
arr.sum()

np.int64(450)

In [ ]:
#Find the minimum value in the same 2D array.
arr = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])
arr.min()

np.int64(10)

In [13]:
#Find the maximum value in the same 2D array.
arr = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])
arr.max()

np.int64(90)

In [14]:
#Find the mean of the entire array.
arr = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])
arr.mean()

np.float64(50.0)

In [15]:
#Find the sum of each row using axis=1.
arr = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])
arr.sum(axis=1)

array([ 60, 150, 240])

In [16]:
#Find the sum of each column using axis=0.
arr = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])
arr.sum(axis=0)

array([120, 150, 180])

In [17]:
#Find the maximum value from each row.
arr = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])
arr.max(axis=1)

array([30, 60, 90])

In [18]:
#Find the minimum value from each column.
arr = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])
arr.min(axis=0)

array([10, 20, 30])

In [19]:
#Find the mean of each row.
arr = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])
arr.mean(axis=1)

array([20., 50., 80.])

In [20]:
#Find the mean of each column.
arr = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])
arr.mean(axis=0)

array([40., 50., 60.])